export const MIN_TITLE_LENGTH = 1;
export const MAX_TITLE_LENGTH = 250;
export const MAX_TEXT_LENGTH = 50000;
export const MIN_DESCRIPTION_LENGTH = 1;
export const MAX_DESCRIPTION_LENGTH = 5000;
export const HOURS_UNTIL_NEAR_NOTE_EXPIRATION = 1;
